import Head from 'next/head'
import { Inter } from 'next/font/google'
// =============== ESTILOS ===============

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 className='titulo'>TP INTEGRADOR...</h1>
        <div className='centrado'>
          <img src='https://media.tenor.com/t3yHhG6m4YkAAAAC/cat-work.gif' alt='gif de gato trabajando'></img>
        </div>
      </main>

    </>
  )
}
